from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import re
import secrets
import hashlib


class DeviceType(str, Enum):
    """انواع دستگاه‌های سورتینگ مجاز در سیستم"""
    SORTER = "Sorter"
    SCANNER = "Scanner"
    CAMERA = "Camera"
    PRINTER = "Printer"
    CONVEYOR = "Conveyor"

    @classmethod
    def from_string(cls, value: str) -> DeviceType:
        """تبدیل رشته به Enum با پشتیبانی از case-insensitive"""
        for member in cls:
            if member.value.lower() == value.lower():
                return member
        raise ValueError(f"Invalid device type: {value}. Must be one of: {', '.join(m.value for m in cls)}")


class DeviceStatus(str, Enum):
    """وضعیت‌های چرخه عمر دستگاه"""
    ACTIVE = "Active"
    INACTIVE = "Inactive"

    @classmethod
    def from_string(cls, value: str) -> DeviceStatus:
        for member in cls:
            if member.value.lower() == value.lower():
                return member
        raise ValueError(f"Invalid device status: {value}. Must be one of: {', '.join(m.value for m in cls)}")


@dataclass(frozen=True)
class DeviceId:
    """
    شناسه یکتای دستگاه - UUID v4
    
    Generated by Core, unguessable.
    """
    value: str

    def __post_init__(self) -> None:
        if not self.value or not self.value.strip():
            raise ValueError("DeviceId cannot be empty")
        
        cleaned = self.value.strip()
        uuid_pattern = re.compile(
            r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
            re.IGNORECASE
        )
        if not uuid_pattern.match(cleaned):
            raise ValueError("DeviceId must be a valid UUID v4")
        
        object.__setattr__(self, "value", cleaned.lower())

    def __str__(self) -> str:
        return self.value

    @classmethod
    def generate(cls) -> DeviceId:
        """تولید DeviceId جدید"""
        import uuid
        return cls(str(uuid.uuid4()))


@dataclass(frozen=True)
class DeviceToken:
    """
    توکن امنیتی دستگاه - Secure random string
    
    Generated by Core during registration, never exposed in logs.
    Stored as hash in database, plain token returned only once at creation.
    """
    value: str

    def __post_init__(self) -> None:
        if not self.value or not self.value.strip():
            raise ValueError("DeviceToken cannot be empty")
        
        cleaned = self.value.strip()
        if len(cleaned) < 32:
            raise ValueError("DeviceToken must be at least 32 characters")
        
        object.__setattr__(self, "value", cleaned)

    def __str__(self) -> str:
        return self.value

    def hash(self) -> str:
        """بازگرداندن هش SHA-256 توکن برای ذخیره‌سازی ایمن"""
        return hashlib.sha256(self.value.encode()).hexdigest()

    @classmethod
    def generate(cls) -> DeviceToken:
        """تولید DeviceToken امن جدید (32 bytes = 64 hex chars)"""
        return cls(secrets.token_hex(32))

    def redacted(self) -> str:
        """نسخه مخفی شده برای لاگینگ"""
        if len(self.value) <= 8:
            return "****"
        return self.value[:4] + "*" * (len(self.value) - 8) + self.value[-4:]


@dataclass(frozen=True)
class LogicalCode:
    """
    کد منطقی دستگاه - یکتا در کل سیستم
    
    Human-readable identifier, unique across system.
    Used for device lookup and operational workflows.
    """
    value: str

    def __post_init__(self) -> None:
        if not self.value or not self.value.strip():
            raise ValueError("LogicalCode cannot be empty")
        
        cleaned = self.value.strip()
        if len(cleaned) > 50:
            raise ValueError("LogicalCode too long (max 50 chars)")
        
        # Only alphanumeric, dash, underscore
        if not re.match(r'^[a-zA-Z0-9_-]+$', cleaned):
            raise ValueError("LogicalCode must contain only alphanumeric, dash, underscore")
        
        object.__setattr__(self, "value", cleaned)

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True)
class ExchangeCenterCode:
    """
    کد مرکز تبادل - 5 رقم
    
    Immutable after device creation.
    """
    value: str

    def __post_init__(self) -> None:
        if not self.value or not self.value.strip():
            raise ValueError("ExchangeCenterCode cannot be empty")
        
        cleaned = self.value.strip()
        if not cleaned.isdigit():
            raise ValueError("ExchangeCenterCode must contain only digits")
        
        if len(cleaned) != 5:
            raise ValueError("ExchangeCenterCode must be exactly 5 digits")
        
        object.__setattr__(self, "value", cleaned)

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True)
class CorrelationId:
    """
    شناسه همبستگی برای ردیابی توزیع‌شده
    فرمت: UUID v4
    """
    value: str

    def __post_init__(self) -> None:
        if not self.value or not self.value.strip():
            raise ValueError("CorrelationId cannot be empty")
        
        cleaned = self.value.strip()
        uuid_pattern = re.compile(
            r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
            re.IGNORECASE
        )
        if not uuid_pattern.match(cleaned):
            raise ValueError("CorrelationId must be a valid UUID v4")
        
        object.__setattr__(self, "value", cleaned.lower())

    def __str__(self) -> str:
        return self.value

    @classmethod
    def generate(cls) -> CorrelationId:
        """تولید CorrelationId جدید"""
        import uuid
        return cls(str(uuid.uuid4()))


__all__ = [
    "DeviceType",
    "DeviceStatus",
    "DeviceId",
    "DeviceToken",
    "LogicalCode",
    "ExchangeCenterCode",
    "CorrelationId",
]